Repository jboss-container-images/jboss-datagrid-7-openshift-image, pull requests merged in 2018-12, with the labels that each got.

#136 Init kerberos env before building images
  Jenkinsfile
Labels: 7.3

#137 Init kerberos env before building images
  Jenkinsfile
Labels: 7.2

#135 Necessary changes for using cekit 2.2.1
  container.yaml
  content_sets.yml
  image.yaml
Labels: 7.3

#134 Necessary changes for using cekit 2.2.1
  container.yaml
  content_sets.yml
  image.yaml
Labels: 7.2

#131 JDG-2346 Better logging when pods are neither not ready nor ready
  services/functional-tests/src/test/java/org/infinispan/online/service/utils/ReadinessCheck.java
Labels: 7.3

#138 Use cct_modules from Sprint 27 (-dev build)
  override-dev.yaml
Labels: 7.2

#142 [JDG-2062] - Export Data Grid stats to Prometheus
  image.yaml
  modules/datagrid/launch/added/launch/prometheus.conf
  modules/datagrid/launch/configure.sh
Labels: 7.3

#141 Data Grid 7.3 templates (for backwards compatibility/support)
  templates/datagrid72-image-stream.json
  templates/datagrid73-basic.json
  templates/datagrid73-https.json
  templates/datagrid73-image-stream.json
  templates/datagrid73-mysql-persistent.json
  templates/datagrid73-mysql.json
  templates/datagrid73-partition.json
  templates/datagrid73-postgresql-persistent.json
  templates/datagrid73-postgresql.json
Labels: 7.3, hold merging

#145 JDG-2062 Export Data Grid stats to Prometheus (fix port expose)
  image.yaml
Labels: 7.3
